### ISSUE TITLE
Some icons throw "the iconName is not correct" error

### ISSUE THREAD

**Issue by m-e-st** [GrimLink/eleventy-plugin-lucide-icons#13]
In my eleventy (v1.0.2) environment, some icon names throw an error ("the iconName is not correct"). The error is reproducible in various of my  projects. Always the same names fail.  For example ...
- "toy-brick" works
- "tractor" fails
.... (all icons between 'tractor' and 'tram-front'  fail too)
- "tram-front" fails
- "trash-2" works

There are other groups of non-working icons too. My workaround is to load the icons directly from lucide-static. But it would be more elegant to use the eleventy shortcut for all icons. (BTW, i checked your 'index.js' and found no reason, why it fails sometimes)

**Comment by GrimLink** [comment]
@m-e-st, this error occurs when attempting to use an icon that does not exist or when using an outdated version of the @grimlink/eleventy-plugin-lucide-icons package that bundles an older version of Lucide.

Upon reviewing your repository (https://github.com/m-e-st/doc.stumpp.name),
I discovered that you're utilizing version [1.0.4](https://github.com/GrimLink/eleventy-plugin-lucide-icons/releases/tag/1.0.4) of the plugin,
which ships with lucide-static 0.257.

The 'tractor' icon is only available in lucide-static 0.265 or later.

![Screenshot 2024-01-24 at 21 29 14](https://github.com/GrimLink/eleventy-plugin-lucide-icons/assets/4387541/03b69dc0-5a60-4ff8-99eb-c43025f65eaa)

To resolve this issue, you can safely update to the version [1.0.6](https://github.com/GrimLink/eleventy-plugin-lucide-icons/releases/tag/1.0.6)

```sh
npm i @grimlink/eleventy-plugin-lucide-icons@1.0.6
```
